#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 2

param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.4
param set-default CA_ROTOR0_PY -0.375
#param sel-default CA_ROTOR0_PZ 0.18
param set-default CA_ROTOR0_KM 1
param set-default CA_ROTOR1_PX -0.4
param set-default CA_ROTOR1_PY 0.375
#param sel-default CA_ROTOR1_PZ 0.18
param set-default CA_ROTOR1_KM 1
param set-default CA_ROTOR2_PX 0.4
param set-default CA_ROTOR2_PY 0.375
#param sel-default CA_ROTOR2_PZ 0.18
param set-default CA_ROTOR2_KM -1
param set-default CA_ROTOR3_PX -0.435
param set-default CA_ROTOR3_PY -0.375
#param sel-default CA_ROTOR3_PZ 0.18
param set-default CA_ROTOR3_KM -1
param set-default CA_ROTOR4_AX 1.0
param set-default CA_ROTOR4_AZ 0.0
param set-default CA_ROTOR4_PX 0.67

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1.0
#param set-default CA_SV_CS3_TYPE 4
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203
#param set-default PWM_MAIN_FUNC9 204

param set-default FW_L1_PERIOD 12
param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.5
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 4  #(2-->4)
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -20  #(-15 --> -20)
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_CRUISE 1
param set-default FW_THR_MAX 1
param set-default FW_THR_MIN 1
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 5

param set-default MPC_ACC_HOR_MAX 5  #(2 --> 5)
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5

param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 1  #(0.75 --> 1)
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_B_TRANS_DUR 8
param set-default VT_TYPE 2

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom